title: My Portfolio
description: A simple portfolio site built with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrishowdev.github.io/" # your GitHub Pages URL

# Build settings
destination: ./_site
markdown: kramdown
theme: jekyll-theme-minimal

sidebar:
  title: "Sample Title"
  nav: test.md
