title: My Portfolio
description: A simple portfolio site built with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrishowdev.github.io/" # your GitHub Pages URL

plugins:
  - jekyll-remote-theme
  
# Build settings
destination: ./_site
markdown: kramdown
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

navigation:
  - name: Readme
    link: test.html
  - name: Another Page
    link: index.html
