title: Christopher Howell
description: Programmer specialising in graphics rendering and c++/c#
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrishowdev.github.io/" # your GitHub Pages URL

plugins:
  - jekyll-remote-theme
  
# Build settings
destination: ./_site
markdown: kramdown
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
    
navigation:
  - name: Resume
    link: /test/
  - name: Projects
    link: /index.html
  - name: Blog
    link: /index.html
  sublist:
      - name: Image
        link: /index.html
      - name: Image
        link: /index.html
