title: Christopher Howell
description: Programmer specialising in graphics rendering and c++/c#
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrishowdev.github.io/" # your GitHub Pages URL

plugins:
  - jekyll-remote-theme
  
# Build settings
destination: ./_site
markdown: kramdown
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

navigation:
  - name: Resume
    link: /test/
  - name: Projects
    link: /index/
  - name: Blog
    link: /index/
